# Generated by Django 4.0.3 on 2022-04-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_ingredient_amount_alter_ingredient_preparation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_steps', to='recipe.recipe')),
            ],
        ),
    ]
