# Generated by Django 4.0.5 on 2022-06-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0008_alter_recipe_author_alter_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recipes', models.ManyToManyField(to='recipe.recipe')),
            ],
        ),
    ]
