# Generated by Django 4.0.5 on 2022-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_author_alter_recipe_cook_time_and_more'),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.recipe'),
        ),
    ]
